In [56]:
from adarank import AdaRank
from metrics import NDCGScorer

In [57]:
import pandas as pd
import numpy  as np

from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer

In [58]:
df = pd.read_excel("data.xlsx", header=0)

In [59]:
tfidf = TfidfVectorizer().fit(df["features"])


In [60]:
df["features"] = df["features"].apply(lambda x : list(tfidf.transform([x]).indices))
df['id_doc'] =  df["id_doc"].apply(lambda x : [x])


In [61]:
df

Qid loinc_num id_doc  rank  \
0      1    1003 3    [1]    30   
1      1   10331 7    [2]    17   
2      1    1250 0    [3]    33   
3      1   13317 3    [4]    56   
4      1   14423 8    [5]    58   
..   ...       ...    ...   ...   
196    3     883 9   [63]    44   
197    3     890 4   [64]     6   
198    3     925 8   [65]     9   
199    3     933 2   [66]    27   
200    3     934 0   [67]     8   

                                              features  
0    [137, 124, 122, 121, 115, 108, 103, 102, 97, 7...  
1                               [140, 117, 72, 24, 23]  
2                           [121, 102, 81, 74, 70, 45]  
3    [153, 144, 126, 125, 124, 116, 108, 98, 85, 76...  
4         [151, 138, 134, 133, 83, 82, 72, 55, 54, 21]  
..                                                 ...  
196                           [140, 72, 63, 24, 23, 2]  
197  [122, 121, 119, 108, 103, 102, 97, 72, 63, 24,...  
198                             [140, 110, 49, 27, 24]  
199                                 [140, 110, 27, 24]  
200                         [142, 110, 95, 69, 51, 24]  

[201 rows x 5 columns]

In [62]:
qid = df["Qid"].to_numpy()
X   = df["features"].to_numpy()
Y   = df["rank"].to_numpy()


In [63]:
Y

array([30, 17, 33, 56, 58, 16,  6,  2,  3,  5, 28, 29, 40, 43, 25, 55, 59,
       65, 54, 66, 61, 53, 62, 37, 24, 11, 27, 31, 45, 46, 18, 38, 41, 36,
       52, 12, 63,  9, 47, 39, 26, 35, 50, 48, 67,  7, 13,  8, 10, 44, 34,
       51, 19, 60,  4, 42, 49, 64, 32,  1, 57, 14, 15, 20, 21, 22, 23, 20,
       42, 11, 57,  5, 43, 64, 21, 23, 66,  8, 22, 14, 13, 29, 62, 56, 59,
       55, 65, 60, 32, 61, 24, 33, 38,  2,  4,  1, 36, 41, 35, 15, 18, 50,
       37, 67, 48, 30, 34, 10, 25, 51, 17, 63, 40, 45, 46, 47, 26,  9, 19,
       49,  7, 27,  3, 31,  6, 28, 16, 58, 39, 44, 12, 54, 53, 52,  7, 47,
       49, 56, 52, 22, 59, 12, 33, 57, 50, 15, 41, 10, 19, 66, 67, 55, 62,
       58, 60, 61, 54, 29, 13, 20, 42, 36, 21, 38, 18, 40, 13, 35, 14, 30,
       63, 24, 26, 17, 32, 25, 28, 34, 53,  1,  2,  4,  3, 11, 46, 45,  5,
       51, 16, 43, 23, 64, 37, 39, 65, 48, 44,  6,  9, 27,  8],
      dtype=int64)

In [64]:
max_len = max(df["features"].apply(lambda x: len(x)))

for i in range(len(X)):
    X[i] =  np.array(X[i] + [0]*(max_len-len(X[i])))


In [65]:
X

array([array([137, 124, 122, 121, 115, 108, 103, 102,  97,  73,  72,  42,  15,
                3,   0])                                                      ,
       array([140, 117,  72,  24,  23,   0,   0,   0,   0,   0,   0,   0,   0,
                0,   0])                                                      ,
       array([121, 102,  81,  74,  70,  45,   0,   0,   0,   0,   0,   0,   0,
                0,   0])                                                      ,
       array([153, 144, 126, 125, 124, 116, 108,  98,  85,  76,  72,  46,  28,
               17,   3], dtype=int32)                                         ,
       array([151, 138, 134, 133,  83,  82,  72,  55,  54,  21,   0,   0,   0,
                0,   0])                                                      ,
       array([142, 140, 110,  72,  63,  58,  27,  24,  23,   2,   0,   0,   0,
                0,   0])                                                      ,
       array([151, 118, 105, 104,  88,  72,  6

In [66]:
model = AdaRank(max_iter=1, scorer=NDCGScorer(K=1), verbose=True)
model.fit(X[:int(len(X)*0.75)], Y[:int(len(Y)*0.75)], qid[:int(len(qid)*0.75)], X[int(len(X)*0.75):], Y[int(len(Y)*0.75):], qid[int(len(qid)*0.75):])

[array([137, 124, 122, 121, 115, 108, 103, 102,  97,  73,  72,  42,  15,
          3,   0])
 array([140, 117,  72,  24,  23,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0])
 array([121, 102,  81,  74,  70,  45,   0,   0,   0,   0,   0,   0,   0,
          0,   0])
 array([153, 144, 126, 125, 124, 116, 108,  98,  85,  76,  72,  46,  28,
         17,   3], dtype=int32)
 array([151, 138, 134, 133,  83,  82,  72,  55,  54,  21,   0,   0,   0,
          0,   0])
 array([142, 140, 110,  72,  63,  58,  27,  24,  23,   2,   0,   0,   0,
          0,   0])
 array([151, 118, 105, 104,  88,  72,  61,  55,  54,   0,   0,   0,   0,
          0,   0])
 array([151, 122, 121, 118, 103, 102,  97,  88,  72,  61,   0,   0,   0,
          0,   0])
 array([151, 122, 121, 118, 107, 106, 103, 102,  97,  88,  72,  68,  61,
          1,   0], dtype=int32)
 array([151, 145, 118,  88,  72,  61,   0,   0,   0,   0,   0,   0,   0,
          0,   0])
 array([151, 122, 121, 103, 102,  97,  72,  52,  33,  